name: LyzardOITC
version: '${project.version}'
main: it.axiid.oitc.OITC
load: STARTUP
author: Axiid
commands:
  oitc:
    description: Main command

  addspawn:
    description: Add spawn command

  setjoinspawn:
    description: Set join spawn

  start:
    description: Start the game